/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppPersonasRouteImport } from './routes/app/personas'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppCompareRouteImport } from './routes/app/compare'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppAccessibilityRouteImport } from './routes/app/accessibility'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as AppAuditsIndexRouteImport } from './routes/app/audits/index'
import { Route as AppAuditsNewRouteImport } from './routes/app/audits/new'
import { Route as AppAuditsIdRouteImport } from './routes/app/audits/$id'
import { Route as AppAuditsIdIndexRouteImport } from './routes/app/audits/$id.index'
import { Route as AppAuditsIdCompareRouteImport } from './routes/app/audits/$id.compare'
import { Route as AppAuditsIdIssuesIssueIdRouteImport } from './routes/app/audits/$id.issues.$issueId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonasRoute = AppPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessibilityRoute = AppAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => AppRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const AppAuditsIndexRoute = AppAuditsIndexRouteImport.update({
  id: '/audits/',
  path: '/audits/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditsNewRoute = AppAuditsNewRouteImport.update({
  id: '/audits/new',
  path: '/audits/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditsIdRoute = AppAuditsIdRouteImport.update({
  id: '/audits/$id',
  path: '/audits/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditsIdIndexRoute = AppAuditsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuditsIdRoute,
} as any)
const AppAuditsIdCompareRoute = AppAuditsIdCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppAuditsIdRoute,
} as any)
const AppAuditsIdIssuesIssueIdRoute =
  AppAuditsIdIssuesIssueIdRouteImport.update({
    id: '/issues/$issueId',
    path: '/issues/$issueId',
    getParentRoute: () => AppAuditsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/pricing': typeof MarketingPricingRoute
  '/app/accessibility': typeof AppAccessibilityRoute
  '/app/chat': typeof AppChatRoute
  '/app/compare': typeof AppCompareRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/personas': typeof AppPersonasRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/': typeof AppIndexRoute
  '/app/audits/$id': typeof AppAuditsIdRouteWithChildren
  '/app/audits/new': typeof AppAuditsNewRoute
  '/app/audits/': typeof AppAuditsIndexRoute
  '/app/audits/$id/compare': typeof AppAuditsIdCompareRoute
  '/app/audits/$id/': typeof AppAuditsIdIndexRoute
  '/app/audits/$id/issues/$issueId': typeof AppAuditsIdIssuesIssueIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/pricing': typeof MarketingPricingRoute
  '/app/accessibility': typeof AppAccessibilityRoute
  '/app/chat': typeof AppChatRoute
  '/app/compare': typeof AppCompareRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/personas': typeof AppPersonasRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof MarketingIndexRoute
  '/app': typeof AppIndexRoute
  '/app/audits/new': typeof AppAuditsNewRoute
  '/app/audits': typeof AppAuditsIndexRoute
  '/app/audits/$id/compare': typeof AppAuditsIdCompareRoute
  '/app/audits/$id': typeof AppAuditsIdIndexRoute
  '/app/audits/$id/issues/$issueId': typeof AppAuditsIdIssuesIssueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/app/accessibility': typeof AppAccessibilityRoute
  '/app/chat': typeof AppChatRoute
  '/app/compare': typeof AppCompareRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/personas': typeof AppPersonasRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/audits/$id': typeof AppAuditsIdRouteWithChildren
  '/app/audits/new': typeof AppAuditsNewRoute
  '/app/audits/': typeof AppAuditsIndexRoute
  '/app/audits/$id/compare': typeof AppAuditsIdCompareRoute
  '/app/audits/$id/': typeof AppAuditsIdIndexRoute
  '/app/audits/$id/issues/$issueId': typeof AppAuditsIdIssuesIssueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/pricing'
    | '/app/accessibility'
    | '/app/chat'
    | '/app/compare'
    | '/app/dashboard'
    | '/app/personas'
    | '/app/settings'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app/'
    | '/app/audits/$id'
    | '/app/audits/new'
    | '/app/audits/'
    | '/app/audits/$id/compare'
    | '/app/audits/$id/'
    | '/app/audits/$id/issues/$issueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/pricing'
    | '/app/accessibility'
    | '/app/chat'
    | '/app/compare'
    | '/app/dashboard'
    | '/app/personas'
    | '/app/settings'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/app'
    | '/app/audits/new'
    | '/app/audits'
    | '/app/audits/$id/compare'
    | '/app/audits/$id'
    | '/app/audits/$id/issues/$issueId'
  id:
    | '__root__'
    | '/_marketing'
    | '/app'
    | '/auth'
    | '/_marketing/pricing'
    | '/app/accessibility'
    | '/app/chat'
    | '/app/compare'
    | '/app/dashboard'
    | '/app/personas'
    | '/app/settings'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_marketing/'
    | '/app/'
    | '/app/audits/$id'
    | '/app/audits/new'
    | '/app/audits/'
    | '/app/audits/$id/compare'
    | '/app/audits/$id/'
    | '/app/audits/$id/issues/$issueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/personas': {
      id: '/app/personas'
      path: '/personas'
      fullPath: '/app/personas'
      preLoaderRoute: typeof AppPersonasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compare': {
      id: '/app/compare'
      path: '/compare'
      fullPath: '/app/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accessibility': {
      id: '/app/accessibility'
      path: '/accessibility'
      fullPath: '/app/accessibility'
      preLoaderRoute: typeof AppAccessibilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/app/audits/': {
      id: '/app/audits/'
      path: '/audits'
      fullPath: '/app/audits/'
      preLoaderRoute: typeof AppAuditsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audits/new': {
      id: '/app/audits/new'
      path: '/audits/new'
      fullPath: '/app/audits/new'
      preLoaderRoute: typeof AppAuditsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audits/$id': {
      id: '/app/audits/$id'
      path: '/audits/$id'
      fullPath: '/app/audits/$id'
      preLoaderRoute: typeof AppAuditsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audits/$id/': {
      id: '/app/audits/$id/'
      path: '/'
      fullPath: '/app/audits/$id/'
      preLoaderRoute: typeof AppAuditsIdIndexRouteImport
      parentRoute: typeof AppAuditsIdRoute
    }
    '/app/audits/$id/compare': {
      id: '/app/audits/$id/compare'
      path: '/compare'
      fullPath: '/app/audits/$id/compare'
      preLoaderRoute: typeof AppAuditsIdCompareRouteImport
      parentRoute: typeof AppAuditsIdRoute
    }
    '/app/audits/$id/issues/$issueId': {
      id: '/app/audits/$id/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/app/audits/$id/issues/$issueId'
      preLoaderRoute: typeof AppAuditsIdIssuesIssueIdRouteImport
      parentRoute: typeof AppAuditsIdRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface AppAuditsIdRouteChildren {
  AppAuditsIdCompareRoute: typeof AppAuditsIdCompareRoute
  AppAuditsIdIndexRoute: typeof AppAuditsIdIndexRoute
  AppAuditsIdIssuesIssueIdRoute: typeof AppAuditsIdIssuesIssueIdRoute
}

const AppAuditsIdRouteChildren: AppAuditsIdRouteChildren = {
  AppAuditsIdCompareRoute: AppAuditsIdCompareRoute,
  AppAuditsIdIndexRoute: AppAuditsIdIndexRoute,
  AppAuditsIdIssuesIssueIdRoute: AppAuditsIdIssuesIssueIdRoute,
}

const AppAuditsIdRouteWithChildren = AppAuditsIdRoute._addFileChildren(
  AppAuditsIdRouteChildren,
)

interface AppRouteChildren {
  AppAccessibilityRoute: typeof AppAccessibilityRoute
  AppChatRoute: typeof AppChatRoute
  AppCompareRoute: typeof AppCompareRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPersonasRoute: typeof AppPersonasRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAuditsIdRoute: typeof AppAuditsIdRouteWithChildren
  AppAuditsNewRoute: typeof AppAuditsNewRoute
  AppAuditsIndexRoute: typeof AppAuditsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessibilityRoute: AppAccessibilityRoute,
  AppChatRoute: AppChatRoute,
  AppCompareRoute: AppCompareRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPersonasRoute: AppPersonasRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAuditsIdRoute: AppAuditsIdRouteWithChildren,
  AppAuditsNewRoute: AppAuditsNewRoute,
  AppAuditsIndexRoute: AppAuditsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
